### ISSUE TITLE
Support for additionalProperties

### ISSUE THREAD

**Issue by PaulBazin** [davidmoten/openapi-to-plantuml#127]
Hello,

Thank you for sharing your project.
Just a question, did you plan to support map definition (https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#model-with-mapdictionary-properties).

Again thank you.

**Comment by davidmoten** [comment]
Glad it's useful. So, two main cases, a map of string to a simple type and a map of string to a complex type. How do you think they should look when rendered by PlantUML?

**Comment by PaulBazin** [comment]
I'm not use to draw uml, but to keep it simple, for string to string map, maybe :
`
class MainClass {
  {field} fieldName : Map{string, string}
}
`
For string to object map, does the following works ?
`
MainClass "fieldName:string" --> "*" MappedClass
`
This is a simple, comprehensive way, but maybe the next proposition is better :
`
class FieldNameMapDefinition {
  {field} key : string
}
FieldNameMapDefinition --> "1" MappedClass : "value"

MainClass --> "*" FieldNameMapDefinition : "fieldName"
`
Even though it is heavier, it is more precise.

**Comment by davidmoten** [comment]
Yep that's what I'm thinking too. 

I drew up examples:
![image](https://user-images.githubusercontent.com/318187/220493065-9570dfa0-3ccb-445c-986c-8e16b9204ee6.png)

```
@startuml

class Thing {
	name: string
	description: string
	properties: string -> string
}

class ThingComplex {
  name: string
  description: string
}

class ThingComplex_Properties {
  key: string {I}
}

class MyValue {
  name: string
  expiry: timestamp
}

ThingComplex --* "*" ThingComplex_Properties: properties
ThingComplex_Properties --> "1" MyValue: value

@enduml
```
or

![image](https://user-images.githubusercontent.com/318187/220493354-1185dd45-b01b-4be2-a2fb-3992690bfb41.png)

**Comment by PaulBazin** [comment]
Just a suggestion : maybe ThinkComplex_Properties should be a struct.

**Comment by davidmoten** [comment]
as in an anonymous class contained within Thing? How do you do that with PlantUML?

**Comment by davidmoten** [comment]
oh you mean this?
![image](https://user-images.githubusercontent.com/318187/220571899-9efcfe80-8e9d-46aa-9abc-f755d500a8f5.png)

**Comment by PaulBazin** [comment]
Yes, that what I meant. Don't know if it is a good Idea, but it keeps domain class clearly separated.

**Comment by davidmoten** [comment]
Refining a bit more, might look like this:
![image](https://user-images.githubusercontent.com/318187/220586305-30b2e52f-0a5e-4745-9e34-ae366d92587d.png)
In general, probably works better to avoid plurals (field name property instead of properties) so we get:
![image](https://user-images.githubusercontent.com/318187/220586919-41e74bd1-c5a2-4d78-8465-0652e83a13ea.png)

**Comment by davidmoten** [comment]
> Yes, that what I meant. Don't know if it is a good Idea, but it keeps domain class clearly separated.

In a way the separation we want is already indicated by the use of a composition arrow (that diamond thing)

**Comment by PaulBazin** [comment]
> Refining a bit more, might look like this: ![image](https://user-images.githubusercontent.com/318187/220586305-30b2e52f-0a5e-4745-9e34-ae366d92587d.png) In general, probably works better to avoid plurals (field name property instead of properties) so we get: ![image](https://user-images.githubusercontent.com/318187/220586919-41e74bd1-c5a2-4d78-8465-0652e83a13ea.png)

Excellent ! Just a thing : the composition is reversed, I think. The black diamond should be on ThinkComplex side of the relation.

**Comment by davidmoten** [comment]
Ah yes, thanks. Diamond on the owner end and arrow on the other.

**Comment by davidmoten** [comment]
Diamond fixed. This will be what I aim for then.

![image](https://user-images.githubusercontent.com/318187/220757840-7c37ca33-0000-4e64-85d3-712f08379a70.png)

```
@startuml

class Thing {
	name: string
	description: string
	property: string -> string
}

class ThingComplex {
  name: string
  description: string
}

struct "ThingComplex/property" {
  key: string {I}
}

class MyValue {
  name: string
  expiry: timestamp
}

ThingComplex *--> "*" "ThingComplex/property": property
"ThingComplex/property" --> "1" MyValue: value

@enduml
```

**Comment by PaulBazin** [comment]
Awesome it is! :)

**Comment by davidmoten** [comment]
Support is added to version 0.1.19 on Maven Central now. I've also updated the online version at https://openapi-to-puml.davidmoten.org/prod/site/index.html. Plug this openapi yaml in there to see it work:

```yaml
openapi: 3.0.1
info:
  title: unit test
  version: 0.0.1
components:
  schemas:
    Thing:
      properties:
        name: 
          type: string
        description:
          type: string
        property:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MyValue"
      required:
      - name
    MyValue:
      properties:
         name: 
           type: string
         expiry:
           type: string
           format: date-time
      required:
      - name
      - expiry
```

**Comment by davidmoten** [comment]
0.1.19 produces;

![image](https://user-images.githubusercontent.com/318187/224454219-591a953f-a708-4d46-bd76-dddae084b28b.png)

![image](https://user-images.githubusercontent.com/318187/224454242-8a661c06-023a-447c-a604-63d1c1e4a71e.png)
